"""empty message

Revision ID: e99a11cdadd2
Revises: 
Create Date: 2019-05-13 14:58:17.174795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99a11cdadd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computers',
    sa.Column('compID', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('reservTil', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('compID')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('computers')
    # ### end Alembic commands ###
